In [ ]:
#Import the libraries
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
import pickle

In [ ]:
#Load the data
data = pd.read_csv('/content/yoga - Sheet1 (5).csv')
data.head(20)

AID                        AName  \
0     1              Padanguli Naman   
1    10           Pooma Titali Asana   
2    12             Manibandha Naman   
3    13            Manibandha Chakra   
4    14                 Kehuni Naman   
5    16               Skandha Chakra   
6    18               Padotthanasana   
7    19               Padachakrasana   
8    20          Pada Sanchalanasana   
9    21         Supta Pawanmuktasana   
10   23      Supta Udarakarshanasana   
11   24      Shava Udarakarshanasana   
12   25                    Naukasana   
13   28           Chakki Chalanasana   
14   29         Nauka Sanchalanasana   
15   30         Kashtha Takshanasana   
16   31                Namaskarasana   
17   34            Udarakarshanasana   
18   42  Nearing And Distant Viewing   
19   43      Shavasana (corpse pose)   

                                          Description  \
0   Sit in the base position with the legs outstre...   
1   Sit in the base position.\nBend the knees and ...   
2   Remain in the base position or a cross-legged ...   
3   Remain in the base position or a comfortable c...   
4   Stage I : Remain in the base position or a cro...   
5   Stage I: Remain in the base position or a cros...   
6   Stage I : Lie in the starting position with th...   
7   Stage I : Lie in the starting position and rel...   
8   Stage I : Lie in the starting position and rel...   
9   Stage I: Lie in the starting position and rela...   
10  Lie in the starting position and relax. Bend t...   
11  Lie in the starting position with the legs and...   
12  Lie in the starting position. Keep the eyes op...   
13  Sit with the legs stretched out in front of th...   
14  Sit with both legs straight in front of the bo...   
15  Squat with the feet flat on the floor about 45...   
16  Squat with the feet flat on the floor about 60...   
17  Squat with the feet apart and the hands on the...   
18  Stand or sit at an open window, preferably wit...   
19  Lie flat on the back with the arms about 15 em...   

                                             Benefits  \
0   This group of asanas is concerned with looseni...   
1   Both stages prepare the legs for mastery of\np...   
2   This group of asanas is concerned with looseni...   
3   The hand and wrist asanas are beneficial for t...   
4   This group of asanas is concerned with looseni...   
5   The shoulder asanas relieve the strain of driv...   
6   This asana strengthens the abdominal muscles a...   
7   Good for the hip joints, obesity, toning of th...   
8   Good for hip and knee joints. Strengthens abdo...   
9   Supta pawanmuktasana strengthens the lower bac...   
10  This asana gives an excellent stretch to the a...   
11  Tightness and tiredness are relieved, especial...   
12  This asana stimulates the muscular, digestive,...   
13  This asana is excellent for toning the nerves ...   
14  This asana has a positive effect on the pelvis...   
15  This asana loosens up the pelvic girdle and to...   
16  This asana has a profound effect on the nerves...   
17  This pose is very useful for abdominal ailment...   
18  This exercise improves the accommodating and f...   
19  This asana relaxes the whole psycho-physiologi...   

                                    Contraindications  \
0                                                 NaN   
1   People with sciatica and sacral conditions\nsh...   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5                                                 NaN   
6   Not to be performed by persons suffer­ing from...   
7   Not to be performed by persons suffering from ...   
8   Not to be performed by persons suffering from ...   
9   Not to be performed by persons suffering from ...   
10                                                NaN   
11  This asana can realign the hip joint. It shoul...   
12                        

In [ ]:
data.shape

(103, 13)

In [ ]:
print(data["Pain"])

0        Joint stiffness and muscle aches
1                     Muscle Relaxation\r
2      Pain Alleviation\r\n\r\n\r\n\r\n\r
3                       Tension Reduction
4                       Joint Flexibility
                      ...                
98                          Toxin Removal
99                 Respiratory Disorders:
100                    Mental Tranquility
101                    Depression Relief:
102              Psycho Neural Activation
Name: Pain, Length: 103, dtype: object


In [ ]:
print(data['Pain'][3])

Tension Reduction


In [ ]:
from IPython.display import Image, display

In [ ]:
# Fill missing values in the 'Photo' column with empty strings
data['Photo'] = data['Photo'].fillna('')

# Convert all values in the 'Photo' column to strings
data['Photo'] = data['Photo'].astype(str)

# Display images
for photo_url in data['Photo']:
    if photo_url.strip() != '':
        display(Image(url=photo_url))

In [ ]:
#the summary of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   AID                103 non-null    int64  
 1   AName              103 non-null    object 
 2   Description        103 non-null    object 
 3   Benefits           101 non-null    object 
 4   Contraindications  68 non-null     object 
 5   Breathing          90 non-null     object 
 6   awareness          87 non-null     object 
 7   You tube Vdo link  0 non-null      float64
 8   Photo              103 non-null    object 
 9   References         0 non-null      float64
 10  Pain               103 non-null    object 
 11  Variations         28 non-null     object 
 12  Level              97 non-null     object 
dtypes: float64(2), int64(1), object(10)
memory usage: 10.6+ KB


In [ ]:
#Create a list that wants to keep
columns = ['AName','Description','Benefits', 'Pain']
print(columns)

['AName', 'Description', 'Benefits', 'Pain']


In [ ]:
# replacing missing/null values with null string

for feature in columns:
  data[feature] = data[feature].fillna('')

# fillna -  i,e fill not available or fill missing values with '' null string

In [ ]:
# combining all the selected features together
combined_features = data['AName']+ ' '+ data['Description']+ ' ' + data['Benefits']+ ' ' +data['Pain']

In [ ]:
print(combined_features)

0      Padanguli Naman Sit in the base position with ...
1      Pooma Titali Asana Sit in the base position.\n...
2      Manibandha Naman Remain in the base position o...
3      Manibandha Chakra Remain in the base position ...
4      Kehuni Naman Stage I : Remain in the base posi...
                             ...                        
98     BHASTRIKA PRANAYAMA Sit in a comfortable medit...
99     KAPALBHATI PRANAYAMA Sit in a comfortable medi...
100    MOORCHHA PRANAYAMA Sit in any comfortable medi...
101    Surya Bheda Pranayama (vitality stimulating br...
102    Chin Mudra (psychic gesture of consciousness) ...
Length: 103, dtype: object


In [ ]:
# converting the text data to feature vector bcoz we cannot find the cosine similarity value with the text data
vectorizer = TfidfVectorizer()

In [ ]:
# here feature_vector will store all the numerical values of combined_features
feature_vector = vectorizer.fit_transform(combined_features)

In [ ]:
# GETTING THE SIMILARITY SCORES USING COSINE SIMILARITY
# getting the score values of all the features_vector
# end result is it will find which values/movies are similar to each other
similarity = cosine_similarity(feature_vector)

In [ ]:
print(similarity)

[[1.         0.36660885 0.68136637 ... 0.33645459 0.27594345 0.28014106]
 [0.36660885 1.         0.34634031 ... 0.31643143 0.22677544 0.33745221]
 [0.68136637 0.34634031 1.         ... 0.3224564  0.26060163 0.33717289]
 ...
 [0.33645459 0.31643143 0.3224564  ... 1.         0.4381244  0.35075536]
 [0.27594345 0.22677544 0.26060163 ... 0.4381244  1.         0.3428698 ]
 [0.28014106 0.33745221 0.33717289 ... 0.35075536 0.3428698  1.        ]]


In [ ]:
print(similarity.shape)
# (index value, similarity between that movie and other movies)
# that means avatar movie is compared with all the other 4802 movies and a similiarity value is found between them

(103, 103)


In [ ]:
# getting the movie name from the user
pain_name = input('Enter the pain for which you need effective yoga poses: ')

Enter the pain for which you need effective yoga poses: Spinal Relief


In [ ]:
# creating a list with all the movie names given in the dataset

# list_of_all_benefits = data['Benefits'].tolist()
# print(list_of_all_benefits)
list_of_all_pain = data['Pain'].tolist()
print(list_of_all_pain)

['Joint stiffness and muscle aches', 'Muscle Relaxation\r', 'Pain Alleviation\r\n\r\n\r\n\r\n\r', 'Tension Reduction', 'Joint Flexibility', 'Strain Reduction', 'Core Strength', 'Hip Flexibility\r', 'Core Toning', 'Digestive Massage', 'Hip Relaxation', 'Spinal Relief', 'Muscular Stimulation', 'Pelvic Toning', 'Abdominal Wellness', 'Upper Back Relief', 'Shoulder Relief', 'Digestive Relief', 'Muscle Fatigue\r\n\r', 'Physical Strain', 'Spinal Alignment', 'Neck Flexibility', 'Back Relief', 'Digestive Stimulation', 'Comfortable Balance', 'Nervous System Relaxation', 'Reproductive Hormone Control', 'Postural Support', 'Prevention of Hernia', 'Mental Stress', 'Nasal Congestion', 'Spiritual Blockage', 'Spinal Alignment', 'Voice Strain', 'Kidney Health', 'Reproductive Discomfort', 'Backache', 'Pelvic Toning', 'Abdominal Strengthening', 'Brain Adaptation', 'Postural Problems', 'Neck Stiffness', 'Abdominal Strengthening', 'Kidney Health', 'Backache', 'Digestive Discomfort', 'Postural Pain', "Write

In [ ]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(pain_name, list_of_all_pain)
# checking whether the entered movie is present in the dataset or not
print(find_close_match)

# he get_close_matches function uses a similarity metric to determine how closely strings match. This metric is based on the "edit distance" between strings. Edit distance measures how many basic operations (such as insertion, deletion, or substitution of a single character) are needed to change one string into another.

['Spinal Relief', 'Spinal Alignment', 'Spinal Alignment']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Spinal Relief


In [ ]:
# find the index of the selected benefit
# select only the rows where the title matches a variable called close_match (here avengers)
index_of_the_pain = data[data.Pain == close_match]['AID'].values[0]
print(index_of_the_pain)

24


In [ ]:
# getting a list of similar poses
# here i am finding the similairity between selected benefit and all the other benefits
similarity_score = list(enumerate(similarity[index_of_the_pain]))
print(similarity_score)


[(0, 0.33161692669913406), (1, 0.3247846326047251), (2, 0.3315372557861059), (3, 0.24080317755309905), (4, 0.335657933390201), (5, 0.32383324869264063), (6, 0.39780872964525366), (7, 0.23732153785467683), (8, 0.32529887289825904), (9, 0.3863942134788742), (10, 0.42362423227672785), (11, 0.4220074678177602), (12, 0.36528600594332916), (13, 0.35356323143520757), (14, 0.2799226103180234), (15, 0.33195846286599257), (16, 0.3825678901566361), (17, 0.3367172304038088), (18, 0.20480791237315998), (19, 0.3294568747523985), (20, 0.27548532781868373), (21, 0.3301349986935673), (22, 0.37547011992163887), (23, 0.36020362416278817), (24, 1.0000000000000002), (25, 0.5218606650053653), (26, 0.4582311812753099), (27, 0.39062881423829326), (28, 0.36162831455267924), (29, 0.30345144594892054), (30, 0.3219722715876939), (31, 0.28546091955524205), (32, 0.37800068740920867), (33, 0.25811707242813237), (34, 0.3540200850986637), (35, 0.39151729329656226), (36, 0.39612197979508357), (37, 0.39774557343306244),

In [ ]:
len(similarity_score)

103

In [ ]:
# sorting the poses based on their similarity score
sorted_similar_poses = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_poses)
# x:x[1] means that x is the similarity_score and 1 basically means the similarity value present at index 1 of the list

[(24, 1.0000000000000002), (25, 0.5218606650053653), (86, 0.47098482678491577), (83, 0.4656109820151226), (26, 0.4582311812753099), (87, 0.4547447447132895), (63, 0.4477979542927047), (72, 0.4458597155675866), (68, 0.4457913281381853), (71, 0.44072746932323514), (78, 0.4380972310346304), (43, 0.4353320793480991), (73, 0.4351992520385853), (42, 0.4345141517706209), (89, 0.42865980683881016), (96, 0.42567790296882946), (81, 0.4252288040605131), (10, 0.42362423227672785), (79, 0.4236111165547012), (82, 0.4235919715428062), (11, 0.4220074678177602), (77, 0.41965655086951953), (84, 0.4134431415043953), (92, 0.412278816294948), (93, 0.4118816920844547), (45, 0.4111292126110071), (67, 0.40865016817521904), (62, 0.4072080423473546), (47, 0.4029650332253887), (85, 0.4023862845106075), (76, 0.4023799743653573), (6, 0.39780872964525366), (37, 0.39774557343306244), (36, 0.39612197979508357), (40, 0.3952255210039102), (80, 0.39191098900142984), (35, 0.39151729329656226), (91, 0.39097013249040036), 

In [ ]:
print('Poses suggested for you: \n')
i = 1
for poses in sorted_similar_poses:
    index = poses[0]
    poseName_from_index = data[data.index == index]['AName'].values[0]
    Photo_URL = data[data.index == index]['Photo'].values[0]
    print(f"{i}. {poseName_from_index}")
    display(Image(url=Photo_URL))
    print('\n')
    i += 1
    if i > 6:
        break


Poses suggested for you: 

1. Sukhasana (easy pose




2. Padmasana (lotus pose)




3. Sirshasana (headstand pose)




4. Sarvangasana (shoulder stand pose)




5. Siddhasana 




6. Niralamba Sirshasana (unsupported headstand pose)


In [ ]:
 model_components = {
      'vectorizer': vectorizer,
      'similarity': similarity,
      'data': data  # Optional: Include data for future reference
  }

In [ ]:
with open('final_trained_model.pkl', 'wb') as f:
    pickle.dump(model_components, f)